### ISSUE TITLE
实现hexo博客中js嵌入的roadmap

### ISSUE THREAD

**Issue by tzayuan** [zhaoyibo/watermark#1]
博主您好, 
想请教下您从hexo搭建到能够在hexo博客上设计实现部署js小工具这整个过程, 
大致需要学习哪些知识和技能？
请问大概的roadmap是怎样的？
（目前对HTML和CSS一知半解，能够根据网上的教程将hexo托管到github page

谢谢！

**Comment by zhaoyibo** [comment]
html、css、js、vue
